### PR TITLE
Remove dependency on OSGi

### PR DESCRIPTION
**Pull request by bertfrees**
Can be tested on super branch https://github.com/daisy/pipeline/compare/master...osgi-less-step-1.

### CODE REVIEW

**Comment by rdeltour** [comment]
what would be a good way to test this?
I went to the `osgi-less-step-1` branch of the super project, ran `make run` but this apparently still launch an OSGi runtime…

**Comment by bertfrees** [comment]
This being only the first step, the whole framework hasn't been fixed yet, and also the assembly (and therefore `make run`) still uses OSGi. What you *can* do is use the XProc libraries outside OSGi. What I have done to test this is adapted the modules-test-helper, xprocspec-runner and xproc-engine-daisy-pipeline components a little so that I can run the XProcSpec tests outside OSGi. There is a system property `org.daisy.pipeline.junit.runners` that controls this. See for example `modules/scripts/parent/pom.xml`: it's currently set to "PaxExam" but you can change it to "OSGiLessRunner".

**Comment by bertfrees** [comment]
I've pushed some more commits to the branch, there were a few issues with the build.

**Comment by rdeltour** [comment]
ok I see, thanks for the clarification!

**Comment by bertfrees** [comment]
Merged in e98833a0b1dd4a2a36e51d051ff6f22e291b5746

**Pull request closed without merging**
